### ISSUE TITLE
I cannot start server

### ISSUE THREAD

**Issue by zhangkaial0320** [Hashnode/Uphack#1]
Thanks for your tutorial https://hashnode.com/post/a-comprehensive-guide-to-coding-a-blockchain-powered-online-community-cji4jh57h001tq5s1qytzxd37
I try to learn it and want to run the server.

However, I met a problem when I run
node server.js

/home/kazhang/Downloads/Uphack/server.js:5
const { parse } = require('url');
      ^

SyntaxError: Unexpected token {
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3

Don't know what's going on. 

I think I setup everything based on your tutorial.

**Comment by zhangkaial0320** [comment]
I figured out the problem, I have to update my nodejs.

**Comment by panda-sandeep** [comment]
Yes. Please use Node 8.9.4 or more to run the server. I will update README to reflect that.
